{% set name = "jupytercad-packages" %}
{% set version = "3.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://pypi.io/packages/source/j/jupytercad_core/jupytercad_core-{{ version }}.tar.gz
    sha256: 6efe690b6cd26bfaccb99fca8df83cd69b78d1fe4857f527aa98c8fea5e303d3
    folder: jupytercad_core
  - url: https://pypi.io/packages/source/j/jupytercad_lab/jupytercad_lab-{{ version }}.tar.gz
    sha256: cf0fcf0144110badc0f89426bbc608186ae7fc6666f52fd23225002def336839
    folder: jupytercad_lab
  - url: https://pypi.io/packages/source/j/jupytercad_app/jupytercad_app-{{ version }}.tar.gz
    sha256: f710b6fab8f37ecceef4a3c166a625a132578b356d84c841df1adfb0aaa5c24a
    folder: jupytercad_app
  - url: https://pypi.io/packages/source/j/jupytercad/jupytercad-{{ version }}.tar.gz
    sha256: 51eb2748cb0e64740dbab8679afd1f1056a6a72fbc042f9b677ce62651bbd88a
    folder: jupytercad

build:
  noarch: python
  number: 0


outputs:
  - name: jupytercad_core
    version: {{ version }}
    build:
      noarch: python
      script: |
        cd jupytercad_core
        python -m pip install . -vv --no-deps --no-build-isolation --ignore-installed --no-index
    requirements:
      host:
        - pip
        - python >=3.8
        - hatchling
        - yarn
        - jupyterlab >=4,<5
        - hatch-jupyter-builder
        - hatch-nodejs-version >=0.3.2
      run:
        - python >=3
        - jupyter_server >=2.0.6,<3
        - jupyter_ydoc >=2,<4
        - pydantic >=2,<3
        - y-py >=0.6,<0.7
        - jupyter-collaboration >=3,<4
    test:
      imports:
        - jupytercad_core
      commands:
        - pip check
        - test -f ${PREFIX}/share/jupyter/labextensions/@jupytercad/jupytercad-core/package.json                            # [unix]
        - if not exist %PREFIX%\\share\\jupyter\\labextensions\\@jupytercad/jupytercad-core\\package.json (exit 1)          # [win]
      requires:
        - pip

  - name: jupytercad_lab
    version: {{ version }}
    build:
      noarch: python
      script: |
        cd jupytercad_lab
        python -m pip install . -vv --no-deps --no-build-isolation --ignore-installed --no-index
    requirements:
      host:
        - pip
        - python >=3.8
        - hatchling
        - yarn
        - jupyterlab >=4,<5
        - hatch-jupyter-builder
        - hatch-nodejs-version >=0.3.2
      run:
        - python >=3.8
        - jupyter_server> =2.0.6,<3
        - jupyter_ydoc >=2,<4
        - jupyter-collaboration >=3,<4
        - ypywidgets >=0.9,<0.10
        - yjs-widgets >=0.3.7,<0.4
        - comm >=0.1.2,<0.2
        - pydantic >=2,<3
        - jupytercad_core
        - jupyterlab >=4,<5
      run_constrained:
        - jupytercad_core ={{ version }}
    test:
      imports:
        - jupytercad_lab.notebook.cad_document
      commands:
        - pip check
        - test -f ${PREFIX}/share/jupyter/labextensions/@jupytercad/jupytercad-lab/package.json                            # [unix]
        - if not exist %PREFIX%\\share\\jupyter\\labextensions\\@jupytercad/jupytercad-lab\\package.json (exit 1)          # [win]
      requires:
        - pip

  - name: jupytercad_app
    version: {{ version }}
    build:
      noarch: python
      script: |
        cd jupytercad_app
        python -m pip install . -vv --no-deps --no-build-isolation --ignore-installed --no-index
      entry_points:
        - jupyter-cad = jupytercad_app.cadapp:main
    requirements:
      host:
        - pip
        - python >=3.8
        - hatchling
        - yarn
        - jupyterlab >=4,<5
        - hatch-jupyter-builder
        - hatch-nodejs-version >=0.3.2
      run:
        - python >=3.8
        - jupyter_server >=2.0.6,<3
        - jupytercad_core
        - jupytercad_lab
      run_constrained:
        - jupyterlab >=4,<5
        - jupytercad_lab ={{ version }}
        - jupytercad_core ={{ version }}
    test:
      imports:
        - jupytercad_app.cadapp
      commands:
        - jupyter cad --version
        - pip check
      requires:
        - pip

  - name: jupytercad
    version: {{ version }}
    build:
      noarch: python
      script: |
        cd jupytercad
        python -m pip install . -vv --no-deps --no-build-isolation --ignore-installed --no-index
    requirements:
      host:
        - pip
        - python >=3.8
        - hatchling
      run:
        - python >=3.8
        - jupytercad_core
        - jupytercad_lab
        - jupytercad_app
      run_constrained:
        - jupytercad_core ={{ version }}
        - jupytercad_lab ={{ version }}
        - jupytercad_app ={{ version }}
    test:
      imports:
        - jupytercad
      commands:
        - pip check
      requires:
        - pip

about:
  home: https://github.com/jupytercad/jupytercad
  summary: A JupyterLab extension for 3D geometry modeling
  description: |
    JupyterCAD is a JupyterLab extension for 3D geometry modeling with collaborative editing support. It is designed to allow multiple people to work on the same file at the same time, and to facilitate discussion and collaboration around the 3D shapes being created.
    JupyterCAD has support for FreeCAD files, which makes it easy to import and export models from FreeCAD. It also has a range of features for creating and manipulating 3D shapes, including a variety of primitives, transformations, and Boolean operations.
  license: BSD-3-Clause
  license_family: BSD
  license_file: jupytercad/LICENSE
  doc_url: https://jupytercad.readthedocs.io/en/latest
  dev_url: https://github.com/jupytercad/jupytercad

extra:
  recipe-maintainers:
    - martinRenou
    - trungleduc
