{% set name = "jupytercad-packages" %}
{% set version = "3.4.3" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://pypi.org/packages/source/j/jupytercad_core/jupytercad_core-{{ version }}.tar.gz
    sha256: afcb863137b2b7d46dcf413d6e6f921d94f7aabbe6789be1dc961e41c20ee330
    folder: jupytercad_core
  - url: https://pypi.org/packages/source/j/jupytercad_lab/jupytercad_lab-{{ version }}.tar.gz
    sha256: 747925cb7f2f306a643fa05cc0d841bba49d49658c00be4c2b4377dd0d795059
    folder: jupytercad_lab
  - url: https://pypi.org/packages/source/j/jupytercad_app/jupytercad_app-{{ version }}.tar.gz
    sha256: 0129b38b04353320a9a9f6475b3b564486feb21a354d03a794451d9d60b8cf5e
    folder: jupytercad_app
  - url: https://pypi.org/packages/source/j/jupytercad_lite/jupytercad_lite-{{ version }}.tar.gz
    sha256: d9b172de77712f7204b2c476295f5c24c9570fe90305480ce3c95a7aa5ae312e
    folder: jupytercad_lite
  - url: https://pypi.org/packages/source/j/jupytercad/jupytercad-{{ version }}.tar.gz
    sha256: d93b812e4148443e8727d063e3d6abdb3685dcfc07eaf615e60784467e519ac5
    folder: jupytercad

build:
  noarch: python
  number: 0


outputs:
  - name: jupytercad-core
    version: {{ version }}
    build:
      noarch: python
      script: |
        cd jupytercad_core
        python -m pip install . -vv --no-deps --no-build-isolation --ignore-installed --no-index
    requirements:
      host:
        - pip
        - python {{ python_min }}
        - hatchling
        - yarn
        - jupyterlab >=4,<5
        - hatch-jupyter-builder
        - hatch-nodejs-version >=0.3.2
      run:
        - python >={{ python_min }}
        - jupyter_ydoc >=4.1.1,<5
        - pydantic >=2,<3
    test:
      commands:
        - pip check
        - test -f ${PREFIX}/share/jupyter/labextensions/@jupytercad/jupytercad-core/package.json                            # [unix]
        - if not exist %PREFIX%\\share\\jupyter\\labextensions\\@jupytercad/jupytercad-core\\package.json (exit 1)          # [win]
      requires:
        - pip

  - name: jupytercad-lab
    version: {{ version }}
    build:
      noarch: python
      script: |
        cd jupytercad_lab
        python -m pip install . -vv --no-deps --no-build-isolation --ignore-installed --no-index
    requirements:
      host:
        - pip
        - python {{ python_min }}
        - hatchling
        - yarn
        - jupyterlab >=4,<5
        - hatch-jupyter-builder
        - hatch-nodejs-version >=0.3.2
      run:
        - python >={{ python_min }}
        - ypywidgets >=0.9,<0.10
        - yjs-widgets >=0.6,<0.7
        - comm >=0.1.2,<0.2
        - pydantic >=2,<3
        - jupytercad-core
      run_constrained:
        - jupytercad-core ={{ version }}
    test:
      imports:
        - jupytercad_lab.notebook.cad_document
      commands:
        - pip check
        - test -f ${PREFIX}/share/jupyter/labextensions/@jupytercad/jupytercad-lab/package.json                            # [unix]
        - if not exist %PREFIX%\\share\\jupyter\\labextensions\\@jupytercad/jupytercad-lab\\package.json (exit 1)          # [win]
      requires:
        - pip

  - name: jupytercad-app
    version: {{ version }}
    build:
      noarch: python
      script: |
        cd jupytercad_app
        python -m pip install . -vv --no-deps --no-build-isolation --ignore-installed --no-index
      entry_points:
        - jupyter-cad = jupytercad_app.cadapp:main
    requirements:
      host:
        - pip
        - python {{ python_min }}
        - hatchling
        - yarn
        - jupyterlab >=4,<5
        - hatch-jupyter-builder
        - hatch-nodejs-version >=0.3.2
      run:
        - python >={{ python_min }}
        - jupyter_server >=2.0.6,<3
        - jupyterlab_server
        - jupytercad-core
        - jupytercad-lab
      run_constrained:
        - jupytercad-lab ={{ version }}
        - jupytercad-core ={{ version }}
    test:
      imports:
        - jupytercad_app.cadapp
      commands:
        - jupyter cad --version
        - pip check
      requires:
        - pip

  - name: jupytercad-lite
    version: {{ version }}
    build:
      noarch: python
      script: |
        cd jupytercad_lite
        python -m pip install . -vv --no-deps --no-build-isolation --ignore-installed --no-index
    requirements:
      host:
        - pip
        - python {{ python_min }}
        - hatchling
      run:
        - python >={{ python_min }}
        - jupytercad-core
        - jupytercad-lab
        - my-jupyter-shared-drive>=0.2.2
      run_constrained:
        - jupytercad-core ={{ version }}
        - jupytercad-lab ={{ version }}
    test:
      imports:
        - jupytercad
      commands:
        - pip check
      requires:
        - pip
        - python {{ python_min }}

  - name: jupytercad
    version: {{ version }}
    build:
      noarch: python
      script: |
        cd jupytercad
        python -m pip install . -vv --no-deps --no-build-isolation --ignore-installed --no-index
    requirements:
      host:
        - pip
        - python {{ python_min }}
        - hatchling
      run:
        - python >={{ python_min }}
        - jupytercad-core
        - jupytercad-lab
        - jupytercad-app
        - jupyter-collaboration >=5,<6
        - jupyter-collaboration-ui >=3,<4
        - jupyter-docprovider >=3,<4
        - jupyter_server_ydoc >=3,<4
        - jupyterlab >=4.3,<5
      run_constrained:
        - jupytercad-core ={{ version }}
        - jupytercad-lab ={{ version }}
        - jupytercad-app ={{ version }}
    test:
      imports:
        - jupytercad
      commands:
        - pip check
      requires:
        - pip
        - python {{ python_min }}

about:
  home: https://github.com/jupytercad/jupytercad
  summary: A JupyterLab extension for 3D geometry modeling
  description: |
    JupyterCAD is a JupyterLab extension for 3D geometry modeling with collaborative editing support. It is designed to allow multiple people to work on the same file at the same time, and to facilitate discussion and collaboration around the 3D shapes being created.
    JupyterCAD has support for FreeCAD files, which makes it easy to import and export models from FreeCAD. It also has a range of features for creating and manipulating 3D shapes, including a variety of primitives, transformations, and Boolean operations.
  license: BSD-3-Clause
  license_family: BSD
  license_file: jupytercad/LICENSE
  doc_url: https://jupytercad.readthedocs.io/en/latest
  dev_url: https://github.com/jupytercad/jupytercad

extra:
  recipe-maintainers:
    - arjxn-py
    - martinRenou
    - trungleduc
