{% set name = "jupytercad-packages" %}
{% set version = "3.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://pypi.org/packages/source/j/jupytercad_core/jupytercad_core-{{ version }}.tar.gz
    sha256: f7defcd795837279fbec5969d7f27674640f563fbbc0a140dc44af0397a43ef2
    folder: jupytercad_core
  - url: https://pypi.org/packages/source/j/jupytercad_lab/jupytercad_lab-{{ version }}.tar.gz
    sha256: a4484392fb5ca7aff81d3233c68dc559dee2094864fed034413339512f90b375
    folder: jupytercad_lab
  - url: https://pypi.org/packages/source/j/jupytercad_app/jupytercad_app-{{ version }}.tar.gz
    sha256: 3b9d36cfd504c5b35b94443a21842ec1651af900e8c898aa8f4c2335a59f27be
    folder: jupytercad_app
  - url: https://pypi.org/packages/source/j/jupytercad/jupytercad-{{ version }}.tar.gz
    sha256: 2ea07b5677294f61b7aaa66d7dc949345438db836429524f9e7bb768208dbf41
    folder: jupytercad

build:
  noarch: python
  number: 0


outputs:
  - name: jupytercad_core
    version: {{ version }}
    build:
      noarch: python
      script: |
        cd jupytercad_core
        python -m pip install . -vv --no-deps --no-build-isolation --ignore-installed --no-index
    requirements:
      host:
        - pip
        - python {{ python_min }}
        - hatchling
        - yarn
        - jupyterlab >=4,<5
        - hatch-jupyter-builder
        - hatch-nodejs-version >=0.3.2
      run:
        - python >={{ python_min }}
        - jupyter_server >=2.0.6,<3
        - jupyter_ydoc >=2,<4
        - pydantic >=2,<3
        - y-py >=0.6,<0.7
        - jupyter-collaboration >=3,<4
    test:
      imports:
        - jupytercad_core
      commands:
        - pip check
        - test -f ${PREFIX}/share/jupyter/labextensions/@jupytercad/jupytercad-core/package.json                            # [unix]
        - if not exist %PREFIX%\\share\\jupyter\\labextensions\\@jupytercad/jupytercad-core\\package.json (exit 1)          # [win]
      requires:
        - pip

  - name: jupytercad_lab
    version: {{ version }}
    build:
      noarch: python
      script: |
        cd jupytercad_lab
        python -m pip install . -vv --no-deps --no-build-isolation --ignore-installed --no-index
    requirements:
      host:
        - pip
        - python {{ python_min }}
        - hatchling
        - yarn
        - jupyterlab >=4,<5
        - hatch-jupyter-builder
        - hatch-nodejs-version >=0.3.2
      run:
        - python >={{ python_min }}
        - jupyter_server> =2.0.6,<3
        - jupyter_ydoc >=2,<4
        - jupyter-collaboration >=3,<4
        - ypywidgets >=0.9,<0.10
        - yjs-widgets >=0.3.7,<0.4
        - comm >=0.1.2,<0.2
        - pydantic >=2,<3
        - jupytercad_core
        - jupyterlab >=4,<5
      run_constrained:
        - jupytercad_core ={{ version }}
    test:
      imports:
        - jupytercad_lab.notebook.cad_document
      commands:
        - pip check
        - test -f ${PREFIX}/share/jupyter/labextensions/@jupytercad/jupytercad-lab/package.json                            # [unix]
        - if not exist %PREFIX%\\share\\jupyter\\labextensions\\@jupytercad/jupytercad-lab\\package.json (exit 1)          # [win]
      requires:
        - pip

  - name: jupytercad_app
    version: {{ version }}
    build:
      noarch: python
      script: |
        cd jupytercad_app
        python -m pip install . -vv --no-deps --no-build-isolation --ignore-installed --no-index
      entry_points:
        - jupyter-cad = jupytercad_app.cadapp:main
    requirements:
      host:
        - pip
        - python {{ python_min }}
        - hatchling
        - yarn
        - jupyterlab >=4,<5
        - hatch-jupyter-builder
        - hatch-nodejs-version >=0.3.2
      run:
        - python >={{ python_min }}
        - jupyter_server >=2.0.6,<3
        - jupytercad_core
        - jupytercad_lab
      run_constrained:
        - jupyterlab >=4,<5
        - jupytercad_lab ={{ version }}
        - jupytercad_core ={{ version }}
    test:
      imports:
        - jupytercad_app.cadapp
      commands:
        - jupyter cad --version
        - pip check
      requires:
        - pip

  - name: jupytercad
    version: {{ version }}
    build:
      noarch: python
      script: |
        cd jupytercad
        python -m pip install . -vv --no-deps --no-build-isolation --ignore-installed --no-index
    requirements:
      host:
        - pip
        - python {{ python_min }}
        - hatchling
      run:
        - python >={{ python_min }}
        - jupytercad_core
        - jupytercad_lab
        - jupytercad_app
      run_constrained:
        - jupytercad_core ={{ version }}
        - jupytercad_lab ={{ version }}
        - jupytercad_app ={{ version }}
    test:
      imports:
        - jupytercad
      commands:
        - pip check
      requires:
        - pip
        - python {{ python_min }}

about:
  home: https://github.com/jupytercad/jupytercad
  summary: A JupyterLab extension for 3D geometry modeling
  description: |
    JupyterCAD is a JupyterLab extension for 3D geometry modeling with collaborative editing support. It is designed to allow multiple people to work on the same file at the same time, and to facilitate discussion and collaboration around the 3D shapes being created.
    JupyterCAD has support for FreeCAD files, which makes it easy to import and export models from FreeCAD. It also has a range of features for creating and manipulating 3D shapes, including a variety of primitives, transformations, and Boolean operations.
  license: BSD-3-Clause
  license_family: BSD
  license_file: jupytercad/LICENSE
  doc_url: https://jupytercad.readthedocs.io/en/latest
  dev_url: https://github.com/jupytercad/jupytercad

extra:
  recipe-maintainers:
    - martinRenou
    - trungleduc
