{% set name = "jupytercad-packages" %}
{% set version = "3.1.5" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://pypi.org/packages/source/j/jupytercad_core/jupytercad_core-{{ version }}.tar.gz
    sha256: 54d413e2fc3c1e095d59f27efbfcbeeb13e9e756cb0bf5809dddb66a296f8467
    folder: jupytercad_core
  - url: https://pypi.org/packages/source/j/jupytercad_lab/jupytercad_lab-{{ version }}.tar.gz
    sha256: 614be225a00098835e76df58d477687f32ebb7d38af8787ec9eb7dbef5baa40d
    folder: jupytercad_lab
  - url: https://pypi.org/packages/source/j/jupytercad_app/jupytercad_app-{{ version }}.tar.gz
    sha256: 633bbdbb0af509b734c9eec1c37e3b0aa67b6b4a79ccdb6af067d20edee549bd
    folder: jupytercad_app
  - url: https://pypi.org/packages/source/j/jupytercad_lite/jupytercad_lite-{{ version }}.tar.gz
    sha256: c0aa761ec2675b58240a0afa49d13728198a7df006905a2b9769a8df2cd198b2
    folder: jupytercad_lite
  - url: https://pypi.org/packages/source/j/jupytercad/jupytercad-{{ version }}.tar.gz
    sha256: 2fa5f4dab84d38c4d050ad31a8fab08e2c0a8f9fdff7ce47005e94a072c25007
    folder: jupytercad

build:
  noarch: python
  number: 0


outputs:
  - name: jupytercad-core
    version: {{ version }}
    build:
      noarch: python
      script: |
        cd jupytercad_core
        python -m pip install . -vv --no-deps --no-build-isolation --ignore-installed --no-index
    requirements:
      host:
        - pip
        - python {{ python_min }}
        - hatchling
        - yarn
        - jupyterlab >=4,<5
        - hatch-jupyter-builder
        - hatch-nodejs-version >=0.3.2
      run:
        - python >={{ python_min }}
        - jupyter_ydoc >=2,<4
        - pydantic >=2,<3
    test:
      commands:
        - pip check
        - test -f ${PREFIX}/share/jupyter/labextensions/@jupytercad/jupytercad-core/package.json                            # [unix]
        - if not exist %PREFIX%\\share\\jupyter\\labextensions\\@jupytercad/jupytercad-core\\package.json (exit 1)          # [win]
      requires:
        - pip

  - name: jupytercad-lab
    version: {{ version }}
    build:
      noarch: python
      script: |
        cd jupytercad_lab
        python -m pip install . -vv --no-deps --no-build-isolation --ignore-installed --no-index
    requirements:
      host:
        - pip
        - python {{ python_min }}
        - hatchling
        - yarn
        - jupyterlab >=4,<5
        - hatch-jupyter-builder
        - hatch-nodejs-version >=0.3.2
      run:
        - python >={{ python_min }}
        - ypywidgets >=0.9,<0.10
        - yjs-widgets >=0.4,<0.5
        - comm >=0.1.2,<0.2
        - pydantic >=2,<3
        - jupytercad-core
      run_constrained:
        - jupytercad-core ={{ version }}
    test:
      imports:
        - jupytercad_lab.notebook.cad_document
      commands:
        - pip check
        - test -f ${PREFIX}/share/jupyter/labextensions/@jupytercad/jupytercad-lab/package.json                            # [unix]
        - if not exist %PREFIX%\\share\\jupyter\\labextensions\\@jupytercad/jupytercad-lab\\package.json (exit 1)          # [win]
      requires:
        - pip

  - name: jupytercad-app
    version: {{ version }}
    build:
      noarch: python
      script: |
        cd jupytercad_app
        python -m pip install . -vv --no-deps --no-build-isolation --ignore-installed --no-index
      entry_points:
        - jupyter-cad = jupytercad_app.cadapp:main
    requirements:
      host:
        - pip
        - python {{ python_min }}
        - hatchling
        - yarn
        - jupyterlab >=4,<5
        - hatch-jupyter-builder
        - hatch-nodejs-version >=0.3.2
      run:
        - python >={{ python_min }}
        - jupyter_server >=2.0.6,<3
        - jupyterlab_server
        - jupytercad-core
        - jupytercad-lab
      run_constrained:
        - jupytercad-lab ={{ version }}
        - jupytercad-core ={{ version }}
    test:
      imports:
        - jupytercad_app.cadapp
      commands:
        - jupyter cad --version
        - pip check
      requires:
        - pip

  - name: jupytercad-lite
    version: {{ version }}
    build:
      noarch: python
      script: |
        cd jupytercad_lite
        python -m pip install . -vv --no-deps --no-build-isolation --ignore-installed --no-index
    requirements:
      host:
        - pip
        - python {{ python_min }}
        - hatchling
      run:
        - python >={{ python_min }}
        - jupytercad-core
        - jupytercad-lab
        - my-jupyter-shared-drive<0.2
      run_constrained:
        - jupytercad-core ={{ version }}
        - jupytercad-lab ={{ version }}
    test:
      imports:
        - jupytercad
      commands:
        - pip check
      requires:
        - pip
        - python {{ python_min }}

  - name: jupytercad
    version: {{ version }}
    build:
      noarch: python
      script: |
        cd jupytercad
        python -m pip install . -vv --no-deps --no-build-isolation --ignore-installed --no-index
    requirements:
      host:
        - pip
        - python {{ python_min }}
        - hatchling
      run:
        - python >={{ python_min }}
        - jupytercad-core
        - jupytercad-lab
        - jupytercad-app
        - jupyter-collaboration >=3,<4
        - jupyter-collaboration-ui >=1,<2
        - jupyter-docprovider >=1,<2
        - jupyter_server_ydoc >=1,<2
        - jupyterlab >=4.3,<5
      run_constrained:
        - jupytercad-core ={{ version }}
        - jupytercad-lab ={{ version }}
        - jupytercad-app ={{ version }}
    test:
      imports:
        - jupytercad
      commands:
        - pip check
      requires:
        - pip
        - python {{ python_min }}

about:
  home: https://github.com/jupytercad/jupytercad
  summary: A JupyterLab extension for 3D geometry modeling
  description: |
    JupyterCAD is a JupyterLab extension for 3D geometry modeling with collaborative editing support. It is designed to allow multiple people to work on the same file at the same time, and to facilitate discussion and collaboration around the 3D shapes being created.
    JupyterCAD has support for FreeCAD files, which makes it easy to import and export models from FreeCAD. It also has a range of features for creating and manipulating 3D shapes, including a variety of primitives, transformations, and Boolean operations.
  license: BSD-3-Clause
  license_family: BSD
  license_file: jupytercad/LICENSE
  doc_url: https://jupytercad.readthedocs.io/en/latest
  dev_url: https://github.com/jupytercad/jupytercad

extra:
  recipe-maintainers:
    - arjxn-py
    - martinRenou
    - trungleduc
