{% set name = "jupytercad" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 4938583bde5a304569970301a04af11c6221d5364543a38ffde4329307a45e66

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  entry_points:
    - jupyter-cad = jupytercad.cadapp:main

requirements:
  host:
    - python >=3.7
    - pip
    - hatchling >=1.4.0
    - hatch-nodejs-version
    - hatch-jupyter-builder
    - datamodel-code-generator
    - jupyterlab >=4,<5
  run:
    - python >=3.7
    - jupyter_server >=2.0.6
    - jupyterlab >=4,<5
    - jupyter-collaboration >=1.0.0,<2
    - ypywidgets >=0.4.1,<0.5.0
    - yjs-widgets >=0.3.4,<0.4
    - comm >=0.1.2,<0.2.0
    - pydantic
    - freecad

test:
  imports:
    - jupytercad
  requires:
    - pip
  commands:
    - jupyter cad --version
    # jupyter_server server extension
    - jupyter server extension list  # [unix]
    - jupyter server extension list 1>server_extensions 2>&1  # [unix]
    - cat server_extensions | grep "jupytercad.*OK"  # [unix]
    # labextensions
    - jupyter labextension list  # [unix]
    - jupyter labextension list 1>labextensions 2>&1  # [unix]
    - cat labextensions | grep "@jupytercad/jupytercad-extension.*OK"  # [unix]

about:
  home: https://github.com/QuantStack/jupytercad
  summary: A JupyterLab extension for 3D geometry modeling
  description: |
    JupyterCAD is a JupyterLab extension for 3D geometry modeling with collaborative editing support. It is designed to allow multiple people to work on the same file at the same time, and to facilitate discussion and collaboration around the 3D shapes being created.
    JupyterCAD has support for FreeCAD files, which makes it easy to import and export models from FreeCAD. It also has a range of features for creating and manipulating 3D shapes, including a variety of primitives, transformations, and Boolean operations.
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  doc_url: https://jupytercad.readthedocs.io/en/latest
  dev_url: https://github.com/QuantStack/jupytercad

extra:
  recipe-maintainers:
    - martinRenou
    - trungleduc
